# Kaggle kernel entry point (generated by kaggle_bridge.py launch; __CONFIG__ is substituted).
import glob
import json
import os
import shutil
import subprocess
import sys
import tarfile
import time
from pathlib import Path

CFG = json.loads(r"""__CONFIG__""")
T0 = time.time()
DEADLINE = T0 + CFG["hours"] * 3600
# Time kept back for the Octave pass: at most a quarter of the session (a 1 h smoke test keeps 15 min).
OCTAVE_RESERVE = min(1.5 * 3600, 0.25 * CFG["hours"] * 3600) if CFG["octave"] else 0
WORK = Path("/kaggle/working")
CODE = Path("/kaggle/tmp/qaari") if Path("/kaggle").exists() else Path("/tmp/qaari")


def log(msg):
    print(f"[{(time.time() - T0) / 60:6.1f} min] {msg}", flush=True)


def sh(cmd, **kw):
    log("$ " + cmd)
    return subprocess.run(cmd, shell=True, **kw)


# 1. code ------------------------------------------------------------------------------------
# Fixed-depth globs: /kaggle/input also holds ~190k Quran-MD WAVs, so never recurse into it.
DEPTHS = ["/kaggle/input/*/", "/kaggle/input/*/*/", "/kaggle/input/*/*/*/", "/kaggle/input/*/*/*/*/"]


def find(name):
    return [h for d in DEPTHS for h in glob.glob(d + name)]


tars = find("qaari_eval.tar.gz")
CODE.mkdir(parents=True, exist_ok=True)
if tars:
    with tarfile.open(tars[0]) as t:
        t.extractall(CODE)
else:
    src = Path(find("app/pipeline.py")[0]).parent.parent
    for item in src.iterdir():
        dst = CODE / item.name
        (shutil.copytree if item.is_dir() else shutil.copy)(item, dst)
text = find("quran-uthmani.json")
cache = Path.home() / ".cache" / "qaari-eval" / "text"
cache.mkdir(parents=True, exist_ok=True)
if text:
    shutil.copy(text[0], cache / "quran-uthmani.json")
log(f"code in {CODE}; config {CFG}")

# 2. dependencies ------------------------------------------------------------------------------
def online(host="pypi.org", port=443, timeout=5.0):
    import socket

    try:
        socket.create_connection((host, port), timeout=timeout).close()
        return True
    except OSError:
        return False


ONLINE = online()
log(f"internet: {'on' if ONLINE else 'OFF (kernel internet disabled; using the attached qaari-eval-deps bundle)'}")
wheels = find("wheels/praat_parselmouth*.whl")
if wheels:  # bundled wheels: deterministic and works offline
    sh(f"{sys.executable} -m pip install -q --no-index --find-links {Path(wheels[0]).parent} {CFG['pip']} "
       "hyperpyyaml ruamel.yaml")
elif ONLINE:
    sh(f"{sys.executable} -m pip install -q {CFG['pip']}")
else:
    raise SystemExit("No internet and no qaari-eval-deps bundle attached: cannot install dependencies.")
hub = find("hf_hub/models--TBOGamer22--wav2vec2-quran-phonetics")
if hub:  # copy (inputs are read-only; HF writes lock files next to the cache)
    dst = Path.home() / ".cache" / "huggingface" / "hub"
    dst.mkdir(parents=True, exist_ok=True)
    for m in Path(hub[0]).parent.iterdir():
        if not (dst / m.name).exists():
            shutil.copytree(m, dst / m.name)
    log(f"model snapshots copied to {dst}")
if not ONLINE:
    os.environ.update(HF_HUB_OFFLINE="1", TRANSFORMERS_OFFLINE="1")
octave_ready = None
if CFG["octave"] and not ONLINE:
    log("Octave pass skipped: apt needs internet. Run octave_bridge.py on the collected rows elsewhere.")
    CFG["octave"] = False
if CFG["octave"]:
    octave_ready = subprocess.Popen(
        "apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends "
        "octave octave-signal > /kaggle/working/apt.log 2>&1", shell=True)

# 3. benchmark processes -------------------------------------------------------------------------
env = dict(os.environ, OMP_NUM_THREADS="1", MKL_NUM_THREADS="1", PYTHONUNBUFFERED="1")
procs = []
for i in range(CFG["procs"]):
    shard = CFG["shard_base"] + i
    out = WORK / f"runs_{CFG['tag']}_{shard:03d}.jsonl"
    cmd = [sys.executable, str(CODE / "benchmarks" / "run_benchmark.py"), "--reciters", *CFG["reciters"],
           "--verses", CFG["verses"], "--modes", *CFG["modes"], "--shard", f"{shard}/{CFG['shard_total']}",
           "--local-root", "/kaggle/input", "--threads", "1", "--output", str(out)]
    procs.append(subprocess.Popen(cmd, cwd=CODE, env=env, stdout=open(WORK / f"bench_{shard:03d}.log", "w"),
                                  stderr=subprocess.STDOUT))
log(f"started {len(procs)} benchmark processes")
while any(p.poll() is None for p in procs):
    if time.time() > DEADLINE - OCTAVE_RESERVE:
        log("deadline reached; stopping benchmark processes (rows so far are kept)")
        for p in procs:
            p.terminate()
        break
    time.sleep(60)
    rows = sum(sum(1 for _ in open(f)) for f in WORK.glob("runs_*.jsonl"))
    log(f"{rows} rows written")

# 4. Octave DSP pass -----------------------------------------------------------------------------
if CFG["octave"]:
    if octave_ready is not None:
        try:
            octave_ready.wait(timeout=900)
        except subprocess.TimeoutExpired:
            octave_ready.kill()
            log("apt-get timed out after 15 min")
    if shutil.which("octave-cli"):
        runs = sorted(str(f) for f in WORK.glob(f"runs_{CFG['tag']}_*.jsonl"))
        out = WORK / f"octave_{CFG['tag']}_{CFG['shard_base']:03d}.jsonl"
        sh(f"{sys.executable} {CODE}/research_agency_lab/compute_bridge/octave_bridge.py {' '.join(runs)} "
           f"--out {out} --local-root /kaggle/input --jobs {CFG['procs']} --modes {','.join(CFG['modes'])} "
           f"> {WORK}/octave.log 2>&1", cwd=CODE)
    else:
        log("octave unavailable (see apt.log)")
log("done")
